#!/bin/bash

testingDir="$(pwd)"

cd "../../ptsrc"

ptBase="$(pwd)"
ptLib="${ptBase}/lib/pt"
ptSemanticDefs=${ptBase}/semantic/semantic.def
ptParserDefs=${ptBase}/parser/parser.def

cd "$testingDir"

> TestResults

passCount=0
failCount=0

for f in ./*.pt
do
  echo "Testing file $(basename $f)"
  echo "############################" >> TestResults
  baseName="$(basename -s .pt ""$f"")"
  echo "$(basename $f):" >> TestResults
  cat ${baseName}.desc >> TestResults
  echo "" >> TestResults
  ssltrace "ptc -t3 -o3 -L ${ptLib} $f" "${ptSemanticDefs}" > "${baseName}.res"
  ssltrace "ptc -t3 -o3 -L ${ptLib} $f" "${ptSemanticDefs}" -i > "${baseName}.resi"
  ssltrace "ptc -t3 -o3 -L ${ptLib} $f" "${ptSemanticDefs}" -e > "${baseName}.rese"
  ssltrace "ptc -t3 -o3 -L ${ptLib} $f" "${ptSemanticDefs}" -r > "${baseName}.resr"
  if [ -e "${baseName}.expe" ]
  then  
    if (diff ${baseName}.expe ${baseName}.rese -qw)
    then
      echo "-e output passed." >> TestResults
      (( passCount += 1 ))
    else
      echo "-e output FAILED." >> TestResults
      (( failCount += 1 ))
    fi
  fi
echo >> TestResults
done

echo "${failCount} test(s) failed, ${passCount} test(s) passed." >> TestResults

cat TestResults

