#!/bin/bash

testingDir="$(pwd)"

cd "../../ptsrc"

ptBase="$(pwd)"
ptLib="${ptBase}/lib/pt"
ptScanDefs=${ptBase}/parser/scan.def

cd "$testingDir"

> TestResults

for f in ./*.pt
do
  echo "Testing file $(basename $f)"
  baseName="$(basename -s .pt ""$f"")"
  cat ${baseName}.desc >> TestResults
  ssltrace "ptc -t1 -o1 -L ${ptLib} $f" "${ptScanDefs}" -e >> "${baseName}.res"
done
