#!/bin/bash

testingDir="$(pwd)"

cd "../../ptsrc"

ptBase="$(pwd)"
ptLib="${ptBase}/lib/pt"
ptScanDefs=${ptBase}/parser/scan.def

cd "$testingDir"

> TestResults

passCount=0
failCount=0

for f in ./*.pt
do
  echo "Testing file $(basename $f)"
  baseName="$(basename -s .pt ""$f"")"
  cat ${baseName}.desc >> TestResults
  ssltrace "ptc -t1 -o1 -L ${ptLib} $f" "${ptScanDefs}" -e > "${baseName}.res"
  if (diff ${baseName}.res ${baseName}.exp -q)
  then
    echo "Test passed." >> TestResults
    echo >> TestResults # blank line
    (( passCount += 1 ))
  else
    echo "Test FAILED." >> TestResults
    (( failCount += 1 ))
  fi
  echo >> TestResults
done

echo "${failCount} test(s) failed, ${passCount} test(s) passed." >> TestResults

